services:
  postgres:
    image: postgres:17-alpine
    container_name: music-postgres
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: