services:
  postgres:
    image: postgres:17-alpine
    container_name: music-postgres
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
        - music-network

  app:
    build: .
    container_name: music-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/music_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./Music:/app/Music:rw
      - ./Images:/app/Images:rw
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - music-network


volumes:
  postgres_data:


networks:
  music-network:
    driver: bridge