spring.datasource.url=jdbc:postgresql://localhost:5433/music_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

server.port=8080

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.vsu.cs.oop2=DEBUG


file.upload.music-path=static/Music/
file.upload.image-path=static/Images/
app.upload.max-audio-size=52428800
app.upload.max-image-size=10485760

spring.jpa.open-in-view=false
spring.datasource.hikari.connection-timeout=30000
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false