spring.datasource.url=jdbc:postgresql://localhost:5433/music_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8080
