# ====================
# DB
# ====================
spring.datasource.url=jdbc:postgresql://localhost:5433/music_db
spring.datasource.username=postgres
spring.datasource.password=root


# ====================
# JPA / HIBERNATE
# ====================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ====================
# THYMELEAF
# ====================
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


# ====================
# \u041D\u0410\u0421\u0422\u0420\u041E\u0419\u041A\u0418 \u041F\u0423\u041B\u0410
# ====================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.open-in-view=false
spring.datasource.hikari.connection-timeout=30000
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false


# ====================
# \u041F\u041E\u0427\u0422\u0410 YANDEX
# ====================
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=elez123456789@yandex.ru
spring.mail.password=agemhofdjcdhgkfl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.mime.charset=UTF-8


# ====================
# \u0421\u0415\u0420\u0412\u0415\u0420 \u0418 \u0420\u0410\u0417\u041C\u0415\u0420\u042B \u0424\u0410\u0419\u041B\u041E\u0412
# ====================
server.port=8080
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB


# ====================
# \u041D\u0410\u0421\u0422\u0420\u041E\u0419\u041A\u0418 \u041F\u0420\u0418\u041B\u041E\u0416\u0415\u041D\u0418\u042F
# ====================
app.base-url=http://localhost:8080
app.email.from-name=Merkury-Music
app.email.verificationTokenExpiryHours = 24
app.resetPassword.lastPasswordResetRequestMinutes = 5
app.resetPassword.TokenExpiryHours = 2
app.upload.max-audio-size=52428800
app.upload.max-image-size=10485760